export const roadmapSteps = [
  {
    number: "01",
    title: "Create Account",
    desc: "Register with your phone number and verify with OTP. Every user is real — keeping our community safe.",
    textCls: "text-[#FF6B6B]",
    bgCls: "bg-[#FF6B6B]/15",
    hoverBg: "hover:bg-[#FFF0F0]",
    hoverBorder: "hover:border-[#FF6B6B]/40",
    hoverShadow: "hover:shadow-[0_12px_40px_#FF6B6B20]",
  },
  {
    number: "02",
    title: "Complete Profile",
    desc: "Add your name, city, and photo. A complete profile helps adopters and owners build trust.",
    textCls: "text-[#FF9500]",
    bgCls: "bg-[#FF9500]/15",
    hoverBg: "hover:bg-[#FFF5E8]",
    hoverBorder: "hover:border-[#FF9500]/40",
    hoverShadow: "hover:shadow-[0_12px_40px_#FF950020]",
  },
  {
    number: "03",
    title: "Find a Pet",
    desc: "Explore pets listed by users. View age, health, vaccines, and location before requesting adoption.",
    textCls: "text-[#34C759]",
    bgCls: "bg-[#34C759]/15",
    hoverBg: "hover:bg-[#F0FFF4]",
    hoverBorder: "hover:border-[#34C759]/40",
    hoverShadow: "hover:shadow-[0_12px_40px_#34C75920]",
  },
  {
    number: "04",
    title: "Post an Animal",
    desc: "Found a stray? Photograph and post the animal for free adoption so someone can give it a loving home.",
    textCls: "text-[#AF52DE]",
    bgCls: "bg-[#AF52DE]/15",
    hoverBg: "hover:bg-[#F8F0FF]",
    hoverBorder: "hover:border-[#AF52DE]/40",
    hoverShadow: "hover:shadow-[0_12px_40px_#AF52DE20]",
  },
  {
    number: "05",
    title: "Manage Requests",
    desc: "Request to adopt or review all applicants as an owner — choose the best home for the animal.",
    textCls: "text-[#5856D6]",
    bgCls: "bg-[#5856D6]/15",
    hoverBg: "hover:bg-[#F0F0FF]",
    hoverBorder: "hover:border-[#5856D6]/40",
    hoverShadow: "hover:shadow-[0_12px_40px_#5856D620]",
  },
  {
    number: "06",
    title: "Complete Adoption",
    desc: "Chat with the owner, discuss details, and finalize responsibly. Adoption is always free on Pawfect.",
    textCls: "text-[#00C7BE]",
    bgCls: "bg-[#00C7BE]/15",
    hoverBg: "hover:bg-[#F0FFFE]",
    hoverBorder: "hover:border-[#00C7BE]/40",
    hoverShadow: "hover:shadow-[0_12px_40px_#00C7BE20]",
  },
];

export const stories = [
  {
    city: "Jaipur",
    name: "Sheru",
    species: "Dog",
    emoji: "🐕",
    author: "Shiva Kumar",
    story:
      "Left near a crowded bazaar, Sheru waited patiently beside a tea stall for days. A shopkeeper clicked his photo and uploaded it on Pawfect. A young couple felt drawn to his gentle eyes — today Sheru runs happily on their terrace, finally safe and loved.",
    colorCls: "text-[#FF6B6B]",
    bgCls: "bg-[#FF6B6B]/10",
    borderCls: "border-[#FF6B6B]",
    blobCls: "bg-[#FF6B6B]/20",
    gradCls: "from-[#FF6B6B]/40 to-[#FF6B6B]/20",
    hoverBorderCls: "hover:border-[#FF6B6B] hover:text-[#FF6B6B]",
  },
  {
    city: "Delhi",
    name: "Moti",
    species: "Dog",
    emoji: "🐶",
    author: "Pankaj Kumar",
    story:
      "On a chilly morning, Moti was found near a bus stop, shivering and hungry. A college student shared his story on Pawfect. A nearby family felt an instant connection and visited him the same evening. Now Moti guards his forever home with pride.",
    colorCls: "text-[#FF9500]",
    bgCls: "bg-[#FF9500]/10",
    borderCls: "border-[#FF9500]",
    blobCls: "bg-[#FF9500]/20",
    gradCls: "from-[#FF9500]/40 to-[#FF9500]/20",
    hoverBorderCls: "hover:border-[#FF9500] hover:text-[#FF9500]",
  },
  {
    city: "Mumbai",
    name: "Gauri",
    species: "Cat",
    emoji: "🐱",
    author: "Shiva Kumar",
    story:
      "During heavy monsoon rains, a frightened white kitten hid under a parked car. A kind auto driver rescued her and posted on Pawfect. A working professional adopted Gauri — now she naps by the window, watching the rain safely from inside her forever home.",
    colorCls: "text-[#AF52DE]",
    bgCls: "bg-[#AF52DE]/10",
    borderCls: "border-[#AF52DE]",
    blobCls: "bg-[#AF52DE]/20",
    gradCls: "from-[#AF52DE]/40 to-[#AF52DE]/20",
    hoverBorderCls: "hover:border-[#AF52DE] hover:text-[#AF52DE]",
  },
  {
    city: "Amritsar",
    name: "Chintu",
    species: "Pup",
    emoji: "🐾",
    author: "Pankaj Kumar",
    story:
      "Near the peaceful lanes of Amritsar, a small pup sat quietly outside a closed shop. A retired uncle searching for companionship saw Chintu's photo and decided to meet him. That meeting changed everything — Chintu now enjoys morning walks and endless affection.",
    colorCls: "text-[#34C759]",
    bgCls: "bg-[#34C759]/10",
    borderCls: "border-[#34C759]",
    blobCls: "bg-[#34C759]/20",
    gradCls: "from-[#34C759]/40 to-[#34C759]/20",
    hoverBorderCls: "hover:border-[#34C759] hover:text-[#34C759]",
  },
];
